### ISSUE TITLE
The details of the model

### ISSUE THREAD

**Issue by tsj-001** [wangys16/FreeSplat#3]
Thanks for your promising work on Gaussian Splatting! After reading the paper, I didn't find the details of the architectures of FreeSplat, such as the layer number and channel number of the ResNet, U-net, and GRU. Could you provide me with some information about them? Thanks!

**Comment by wangys16** [comment]
We have released our model. Basically, we learn from SimpleRecon in designing a low-cost cost-volume based backbone. You can check the model details in our code.

**Comment by tsj-001** [comment]
Thanks for your response! I will check it in the code.
