### ISSUE TITLE
About offset_xy

### ISSUE THREAD

**Issue by fankeyu123** [wangys16/FreeSplat#4]
Why set offset_xy to 0?
<img width="758" alt="Snipaste_2024-10-26_11-16-19" src="https://github.com/user-attachments/assets/583e44e2-5436-446e-b5ed-9550351ae299">

**Comment by fankeyu123** [comment]
还有就是这里的内参为什么这么处理呢，为什么还要除以4呢，按理说拟传入的已经是归一化内参了
<img width="475" alt="Snipaste_2024-10-26_11-23-12" src="https://github.com/user-attachments/assets/a713e841-7518-46ba-bd68-1e63a35131a6">

**Comment by wangys16** [comment]
Hello, about the offset_xy, we remove it to simplify the alignment in our PTF module. You can also try the ablation of adding it similarly as in pixelsplat. For the intrinsics, since we follow SimpleRecon in computing the cost volume with 1/4 resolution, we need to multiply it with w//4 and h//4.

**Comment by fankeyu123** [comment]
感谢回答！我还有个问题就是这里map_pdf_to_opacity您是并没有使用吗，我看您config里对initial和final都设置为0
![image](https://github.com/user-attachments/assets/d02d9a3a-9070-4762-bd90-bf5afd70187c)

**Comment by wangys16** [comment]
No, we did not use the map_pdf_to_opactiy function.
